/*
 * EnvViewPanel.java
 *
 * Created on May 27, 2002, 11:28 AM
 */

package EnvView;

import EnvModel.*;
/**
 *
 * @author  eu779
 */

/**Thsi is the view of the environment ONLY. It takes just the
 *state of the environment and displays it.
 *Interestingly if we want to click on various parts of the
 *environment for control it would be the controller as well.
 */
public class EnvViewPanel extends javax.swing.JPanel {

    /** Creates new form EnvViewPanel */
    public EnvViewPanel (State state) {
        initComponents();
        this.state = state;
    }

    /*Set the state which this environment view will display.
     *At this level the state is abstaract*/
    void setState(State state) {
        this.state = state;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        
        setLayout(new java.awt.BorderLayout());
        
        setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.LOWERED));
        setBackground(java.awt.Color.red);
        setPreferredSize(new java.awt.Dimension(300, 300));
        setName("Environment View");
    }//GEN-END:initComponents

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    /**Specific Environment Variables */
   
    //The environment state that we're interested in
    State state;
}
