package EnvController.PredatorEnvController;

/*
 * PredatorRunPanel.java
 *
 * Created on 05 June 2002, 19:48
 */


/**
 *
 * @author  Chris Child
 */
public class PredatorRunPanel extends javax.swing.JPanel {

    PredatorEnvApp controller;
    /** Creates new form PredatorRunPanel */
    public PredatorRunPanel(PredatorEnvApp controller) {
        initComponents();
        this.controller = controller;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        run1Cycle = new javax.swing.JButton();
        startRunning = new javax.swing.JButton();
        stopRunning = new javax.swing.JButton();
        
        setLayout(new java.awt.BorderLayout());
        
        run1Cycle.setText("Run 1 Cycle");
        run1Cycle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                run1CycleActionPerformed(evt);
            }
        });
        
        add(run1Cycle, java.awt.BorderLayout.NORTH);
        
        startRunning.setText("Start Running");
        startRunning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startRunningActionPerformed(evt);
            }
        });
        
        add(startRunning, java.awt.BorderLayout.CENTER);
        
        stopRunning.setText("Stop Running");
        stopRunning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopRunningActionPerformed(evt);
            }
        });
        
        add(stopRunning, java.awt.BorderLayout.SOUTH);
        
    }//GEN-END:initComponents

    private void stopRunningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopRunningActionPerformed
        // Add your handling code here:
        controller.stopRunning();
    }//GEN-LAST:event_stopRunningActionPerformed

    private void startRunningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startRunningActionPerformed
        // Add your handling code here:
        controller.startRunning();
    }//GEN-LAST:event_startRunningActionPerformed

    private void run1CycleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_run1CycleActionPerformed
        // Add your handling code here:
        controller.run1Cycle();
    }//GEN-LAST:event_run1CycleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton run1Cycle;
    private javax.swing.JButton startRunning;
    private javax.swing.JButton stopRunning;
    // End of variables declaration//GEN-END:variables

}
